const womanUrls = [
  "/avatars/woman.png",
  "/avatars/woman1.png",
  "/avatars/woman2.png",
  "/avatars/woman3.png",
  "/avatars/woman4.png",
  "/avatars/woman5.png",
  "/avatars/woman6.png",
  "/avatars/woman7.png",
  "/avatars/woman8.png",
  "/avatars/woman9.png",
  "/avatars/woman10.png",
  "/avatars/woman11.png",
  "/avatars/woman12.png",
  "/avatars/woman13.png",
  "/avatars/woman14.png",
  "/avatars/woman15.png",
  "/avatars/woman16.png",
  "/avatars/woman17.png",
  "/avatars/woman18.png",
  "/avatars/woman19.png",
  "/avatars/woman20.png",
  "/avatars/woman21.png",
  "/avatars/woman22.png",
  "/avatars/woman23.png",
  "/avatars/woman24.png",
  "/avatars/woman25.png",
];

export default womanUrls;
