site_name: Pollux | MDS

repo_name: "2023-2-Pollux"
repo_url: "https://github.com/FGA0138-MDS-Ajax/2023-2-POLLUX"

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    
  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: lime
      accent:  indigo

    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: lime
      accent:  indigo

nav :
  - Início : index.md
  - Visão do Produto: 
    - Documento de Visão: documentoVisao.md
    - Declaração de Escopo: escopo.md
    - Documente de Arquitetura: arquitetura.md
  - Sprints : sprints.md
  
